# Generated by Django 4.1.3 on 2022-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Plans', models.CharField(max_length=30)),
                ('Active_Investment_Plans', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='Withdrawals',
        ),
    ]
