# Generated by Django 4.1.3 on 2022-11-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_investment_plans_remove_transactions_withdrawals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='Bonus',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='Deposit',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='Profit',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='Referral_Bonus',
        ),
    ]
