# Generated by Django 4.1.3 on 2022-11-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_remove_transactions_amount_remove_transactions_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(max_length=4)),
                ('Profit', models.FloatField(max_length=30)),
                ('Bonus', models.FloatField(max_length=30)),
                ('Referral_Bonus', models.FloatField(max_length=30)),
                ('Deposit', models.FloatField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Investment_Plans',
            new_name='Users_Investment',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
