# Generated by Django 4.1.3 on 2022-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0004_users_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_balance',
            name='Withdrawals',
            field=models.FloatField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
