# Generated by Django 4.1.3 on 2022-11-14 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptoapp', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_balance',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_investment',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users_balance',
            name='Amount',
            field=models.FloatField(default=0.0, max_length=4),
        ),
        migrations.AlterField(
            model_name='users_balance',
            name='Bonus',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balance',
            name='Deposit',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balance',
            name='Profit',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balance',
            name='Referral_Bonus',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balance',
            name='Withdrawals',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='users_investment',
            name='Active_Investment_Plans',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='users_investment',
            name='Total_Plans',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
