# Generated by Django 4.1.3 on 2022-11-14 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptoapp', '0012_users_investment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_balance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users_investment',
            name='user',
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Plans', models.CharField(default='0', max_length=30)),
                ('Active_Investment_Plans', models.CharField(default='0', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
