# Generated by Django 4.1.3 on 2022-11-14 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptoapp', '0014_users_balance_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_Balance',
            new_name='Balance',
        ),
    ]
