# Generated by Django 4.1.3 on 2022-11-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0016_users_balanc_delete_users_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_balanc',
            name='Amount',
            field=models.FloatField(default='0', max_length=4),
        ),
    ]
