# Generated by Django 4.1.3 on 2022-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0018_alter_users_balanc_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_balanc',
            name='Amount',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
