# Generated by Django 4.1.3 on 2022-11-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0020_alter_users_balanc_bonus_alter_users_balanc_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_balanc',
            name='Amount',
            field=models.FloatField(default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Bonus',
            field=models.FloatField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Deposit',
            field=models.FloatField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Profit',
            field=models.FloatField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Referral_Bonus',
            field=models.FloatField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Withdrawals',
            field=models.FloatField(default='0', max_length=30),
        ),
    ]
