# Generated by Django 4.1.3 on 2022-11-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0021_alter_users_balanc_amount_alter_users_balanc_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_balanc',
            name='Amount',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
