# Generated by Django 4.1.3 on 2022-11-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0023_alter_users_balanc_bonus_alter_users_balanc_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_balanc',
            name='Bonus',
            field=models.FloatField(default=10.0, max_length=30),
        ),
    ]
