# Generated by Django 4.1.3 on 2022-11-16 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptoapp', '0024_alter_users_balanc_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='Active_Investment_Plans',
            field=models.CharField(default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='Total_Plans',
            field=models.CharField(default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Amount',
            field=models.FloatField(default=0.0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Bonus',
            field=models.FloatField(default=10.0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Deposit',
            field=models.FloatField(default=0.0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Profit',
            field=models.FloatField(default=0.0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Referral_Bonus',
            field=models.FloatField(default=0.0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Withdrawals',
            field=models.FloatField(default=0.0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
