# Generated by Django 4.1.3 on 2022-11-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0026_alter_investment_active_investment_plans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='Total_Plans',
            field=models.CharField(default='0', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Amount',
            field=models.FloatField(default=0.0, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='users_balanc',
            name='Bonus',
            field=models.FloatField(default=10.0, editable=False, max_length=30),
        ),
    ]
