# Generated by Django 4.1.3 on 2022-11-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0028_alter_investment_total_plans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_balanc',
            name='Amount',
        ),
    ]
