# Generated by Django 4.1.3 on 2022-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0029_remove_users_balanc_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_balanc',
            name='Amount',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
