# Generated by Django 4.1.3 on 2022-11-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0030_users_balanc_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='default_miner.png', upload_to='profile_pics')),
                ('Machine_Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField(max_length=10)),
                ('Profit', models.CharField(max_length=40)),
            ],
        ),
    ]
