# Generated by Django 4.1.3 on 2022-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0031_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
