# Generated by Django 4.1.3 on 2022-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0032_alter_machines_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Price',
            field=models.FloatField(max_length=10),
        ),
    ]
