# Generated by Django 4.1.3 on 2022-11-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0034_rename_machine_name_machines_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deluxe_Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='default_miner.png', upload_to='profile_pics')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.FloatField(max_length=10)),
                ('Profit', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Exclusive_Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='default_miner.png', upload_to='profile_pics')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.FloatField(max_length=10)),
                ('Profit', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Machines',
            new_name='Basic_Machines',
        ),
    ]
