# Generated by Django 4.1.3 on 2022-11-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0038_withdrawal_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal_password',
            old_name='password',
            new_name='password3',
        ),
    ]
