# Generated by Django 4.1.3 on 2022-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0040_rename_password3_withdrawal_password_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal_password',
            name='password3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
