# Generated by Django 4.1.3 on 2022-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0041_withdrawal_password_password3'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal_password',
            name='Wallet_Address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
