# Generated by Django 4.1.3 on 2022-11-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0043_request_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remaining_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(default=0, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='Amount',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
