# Generated by Django 4.1.3 on 2022-11-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0044_remaining_b_alter_request_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='remaining_b',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remaining_b',
            name='Amount',
            field=models.FloatField(max_length=30),
        ),
    ]
