# Generated by Django 4.1.3 on 2022-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0045_remaining_b_user_alter_remaining_b_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remaining_b',
            name='Amount',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='request',
            name='Amount',
            field=models.FloatField(max_length=30),
        ),
    ]
