# Generated by Django 4.1.3 on 2022-11-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0046_alter_remaining_b_amount_alter_request_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remaining_B',
        ),
    ]
