# Generated by Django 4.1.3 on 2022-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0054_withdrawal_request_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal_request',
            name='Charge',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
