# Generated by Django 4.1.3 on 2022-11-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0055_withdrawal_request_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal_request',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
