# Generated by Django 4.1.3 on 2022-11-20 20:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptoapp', '0057_rename_apprroved_withdrawal_request_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(default=0.0, max_length=4)),
                ('Profit', models.FloatField(default=0.0, max_length=30)),
                ('Bonus', models.FloatField(default=10.0, max_length=30)),
                ('Referral_Bonus', models.FloatField(default=0.0, max_length=30)),
                ('Deposit', models.FloatField(default=0.0, max_length=30)),
                ('Withdrawals', models.FloatField(default=0.0, max_length=30)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Users_Balanc',
        ),
    ]
