# Generated by Django 4.1.3 on 2022-11-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0059_rename_charge_withdrawal_request_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal_request',
            name='Return_Amount',
            field=models.FloatField(max_length=20),
        ),
    ]
