# Generated by Django 4.1.3 on 2022-11-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0060_alter_withdrawal_request_return_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal_request',
            old_name='Approved',
            new_name='Fund_Sent',
        ),
    ]
