# Generated by Django 4.1.3 on 2022-11-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptoapp', '0061_rename_approved_withdrawal_request_fund_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal_password',
            name='username',
        ),
        migrations.AddField(
            model_name='withdrawal_password',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
