# Generated by Django 4.1.3 on 2022-11-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0062_remove_withdrawal_password_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal_request',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
