# Generated by Django 4.1.3 on 2022-11-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0063_alter_withdrawal_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal_password',
            name='user',
        ),
        migrations.AddField(
            model_name='withdrawal_password',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
