# Generated by Django 4.1.3 on 2022-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0066_remove_withdrawal_password_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remaining_Balancet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remaining', models.FloatField(max_length=30)),
            ],
        ),
    ]
