# Generated by Django 4.1.3 on 2022-11-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0067_remaining_balancet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remaining_Balancet',
        ),
    ]
