# Generated by Django 4.1.3 on 2022-11-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0070_remaining_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remaining_balance',
            name='Amount',
            field=models.FloatField(default=0.0, max_length=30),
        ),
    ]
