# Generated by Django 4.1.3 on 2022-11-22 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0072_deposit_delete_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
