# Generated by Django 4.1.3 on 2022-11-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0073_deposit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.FloatField(max_length=10)),
            ],
        ),
    ]
