# Generated by Django 4.1.3 on 2022-12-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0075_users_machine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_machine',
            name='Revenue',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
