# Generated by Django 4.1.3 on 2022-12-03 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0078_deposit_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_machine',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
