# Generated by Django 4.1.3 on 2022-12-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0081_deposit_records_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_machine',
            name='Profit',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users_machine',
            name='Price',
            field=models.FloatField(max_length=100),
        ),
    ]
