# Generated by Django 3.2.16 on 2022-12-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0084_test_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
